import { FIFTEEN_MINUTES, FIVE_MINUTES, TEN_MINUTES, THIRTY_DAYS } from '../utils/date-time';

export const JWT_CONFIG = {
  EXPIRES_IN: FIFTEEN_MINUTES,
  REFRESH_EXPIRES_IN: THIRTY_DAYS,
  RESET_EXPIRES_IN: TEN_MINUTES,
  MFA_LOGIN_EXPIRES_IN: FIVE_MINUTES,
};
