const httpConfig = () => ({
  // Success responses
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,

  // Client error responses
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,

  // Server error responses
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,

  // Custom Enterprise Status Codes (using 4xx and 5xx ranges)
  VALIDATION_ERROR: 422,
  BUSINESS_RULE_VIOLATION: 422,
  RATE_LIMIT_EXCEEDED: 429,
  QUOTA_EXCEEDED: 429,
  ACCOUNT_LOCKED: 423,
  ACCOUNT_DISABLED: 403,
  INSUFFICIENT_PERMISSIONS: 403,
  RESOURCE_CONFLICT: 409,
  RESOURCE_LOCKED: 423,
  RESOURCE_QUOTA_EXCEEDED: 429,
  EXTERNAL_SERVICE_ERROR: 502,
  EXTERNAL_SERVICE_TIMEOUT: 504,
  EXTERNAL_SERVICE_UNAVAILABLE: 503,
  DATABASE_ERROR: 500,
  CACHE_ERROR: 500,
  FILE_UPLOAD_ERROR: 413,
  FILE_PROCESSING_ERROR: 422,
  SECURITY_VIOLATION: 403,
  MAINTENANCE_MODE: 503,
  CONFIGURATION_ERROR: 500,
  DEPENDENCY_UNAVAILABLE: 503,
  RESOURCE_EXHAUSTED: 503,
  COMPLIANCE_VIOLATION: 451,
  LEGAL_RESTRICTION: 451,
  PRIVACY_POLICY_VIOLATION: 451,
  GDPR_VIOLATION: 451,
  CCPA_VIOLATION: 451,
});

export const HTTPSTATUS = httpConfig();

export type HttpStatusCodeType = (typeof HTTPSTATUS)[keyof typeof HTTPSTATUS];
