export const ErrorCodeEnum = {
  // Authentication & Authorization Errors
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_NOT_FOUND: 'AUTH_NOT_FOUND',
  AUTH_TOO_MANY_ATTEMPTS: 'AUTH_TOO_MANY_ATTEMPTS',
  AUTH_UNAUTHORIZED_ACCESS: 'AUTH_UNAUTHORIZED_ACCESS',
  AUTH_TOKEN_NOT_FOUND: 'AUTH_TOKEN_NOT_FOUND',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_ACCOUNT_PENDING_VERIFICATION: 'AUTH_ACCOUNT_PENDING_VERIFICATION',
  AUTH_PASSWORD_TOO_WEAK: 'AUTH_PASSWORD_TOO_WEAK',
  AUTH_PASSWORD_RESET_EXPIRED: 'AUTH_PASSWORD_RESET_EXPIRED',
  AUTH_2FA_REQUIRED: 'AUTH_2FA_REQUIRED',
  AUTH_2FA_INVALID: 'AUTH_2FA_INVALID',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',

  // Access Control & Permissions
  ACCESS_FORBIDDEN: 'ACCESS_FORBIDDEN',
  ACCESS_UNAUTHORIZED: 'ACCESS_UNAUTHORIZED',
  ACCESS_INSUFFICIENT_PERMISSIONS: 'ACCESS_INSUFFICIENT_PERMISSIONS',
  ACCESS_ROLE_REQUIRED: 'ACCESS_ROLE_REQUIRED',
  ACCESS_RESOURCE_OWNER_REQUIRED: 'ACCESS_RESOURCE_OWNER_REQUIRED',
  ACCESS_IP_BLOCKED: 'ACCESS_IP_BLOCKED',
  ACCESS_GEO_BLOCKED: 'ACCESS_GEO_BLOCKED',

  // Validation Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
  VALIDATION_INVALID_EMAIL: 'VALIDATION_INVALID_EMAIL',
  VALIDATION_INVALID_PHONE: 'VALIDATION_INVALID_PHONE',
  VALIDATION_INVALID_URL: 'VALIDATION_INVALID_URL',
  VALIDATION_INVALID_DATE: 'VALIDATION_INVALID_DATE',
  VALIDATION_INVALID_NUMBER: 'VALIDATION_INVALID_NUMBER',
  VALIDATION_INVALID_BOOLEAN: 'VALIDATION_INVALID_BOOLEAN',
  VALIDATION_INVALID_UUID: 'VALIDATION_INVALID_UUID',
  VALIDATION_STRING_TOO_LONG: 'VALIDATION_STRING_TOO_LONG',
  VALIDATION_STRING_TOO_SHORT: 'VALIDATION_STRING_TOO_SHORT',
  VALIDATION_NUMBER_TOO_LARGE: 'VALIDATION_NUMBER_TOO_LARGE',
  VALIDATION_NUMBER_TOO_SMALL: 'VALIDATION_NUMBER_TOO_SMALL',
  VALIDATION_ARRAY_TOO_LONG: 'VALIDATION_ARRAY_TOO_LONG',
  VALIDATION_ARRAY_TOO_SHORT: 'VALIDATION_ARRAY_TOO_SHORT',
  VALIDATION_UNIQUE_CONSTRAINT: 'VALIDATION_UNIQUE_CONSTRAINT',
  VALIDATION_FOREIGN_KEY_CONSTRAINT: 'VALIDATION_FOREIGN_KEY_CONSTRAINT',

  // Resource Management
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RESOURCE_LOCKED: 'RESOURCE_LOCKED',
  RESOURCE_DELETED: 'RESOURCE_DELETED',
  RESOURCE_ARCHIVED: 'RESOURCE_ARCHIVED',
  RESOURCE_VERSION_MISMATCH: 'RESOURCE_VERSION_MISMATCH',
  RESOURCE_QUOTA_EXCEEDED: 'RESOURCE_QUOTA_EXCEEDED',
  RESOURCE_SIZE_EXCEEDED: 'RESOURCE_SIZE_EXCEEDED',
  RESOURCE_TYPE_NOT_SUPPORTED: 'RESOURCE_TYPE_NOT_SUPPORTED',
  RESOURCE_CORRUPTED: 'RESOURCE_CORRUPTED',
  RESOURCE_ACCESS_DENIED: 'RESOURCE_ACCESS_DENIED',
  RESOURCE_NOT_AVAILABLE: 'RESOURCE_NOT_AVAILABLE',

  // Business Logic Errors
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  BUSINESS_INVALID_STATE: 'BUSINESS_INVALID_STATE',
  BUSINESS_OPERATION_NOT_ALLOWED: 'BUSINESS_OPERATION_NOT_ALLOWED',
  BUSINESS_DEPENDENCY_MISSING: 'BUSINESS_DEPENDENCY_MISSING',
  BUSINESS_CIRCULAR_DEPENDENCY: 'BUSINESS_CIRCULAR_DEPENDENCY',
  BUSINESS_INSUFFICIENT_FUNDS: 'BUSINESS_INSUFFICIENT_FUNDS',
  BUSINESS_PAYMENT_FAILED: 'BUSINESS_PAYMENT_FAILED',
  BUSINESS_SUBSCRIPTION_EXPIRED: 'BUSINESS_SUBSCRIPTION_EXPIRED',
  BUSINESS_LICENSE_EXPIRED: 'BUSINESS_LICENSE_EXPIRED',
  BUSINESS_QUOTA_EXCEEDED: 'BUSINESS_QUOTA_EXCEEDED',

  // External Service Errors
  EXTERNAL_SERVICE_UNAVAILABLE: 'EXTERNAL_SERVICE_UNAVAILABLE',
  EXTERNAL_SERVICE_TIMEOUT: 'EXTERNAL_SERVICE_TIMEOUT',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  EXTERNAL_SERVICE_RATE_LIMITED: 'EXTERNAL_SERVICE_RATE_LIMITED',
  EXTERNAL_SERVICE_AUTH_FAILED: 'EXTERNAL_SERVICE_AUTH_FAILED',
  EXTERNAL_SERVICE_INVALID_RESPONSE: 'EXTERNAL_SERVICE_INVALID_RESPONSE',
  EXTERNAL_SERVICE_QUOTA_EXCEEDED: 'EXTERNAL_SERVICE_QUOTA_EXCEEDED',

  // Database Errors
  DATABASE_CONNECTION_FAILED: 'DATABASE_CONNECTION_FAILED',
  DATABASE_QUERY_FAILED: 'DATABASE_QUERY_FAILED',
  DATABASE_TRANSACTION_FAILED: 'DATABASE_TRANSACTION_FAILED',
  DATABASE_CONSTRAINT_VIOLATION: 'DATABASE_CONSTRAINT_VIOLATION',
  DATABASE_DEADLOCK: 'DATABASE_DEADLOCK',
  DATABASE_TIMEOUT: 'DATABASE_TIMEOUT',
  DATABASE_MIGRATION_FAILED: 'DATABASE_MIGRATION_FAILED',

  // File & Storage Errors
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_SUPPORTED: 'FILE_TYPE_NOT_SUPPORTED',
  FILE_CORRUPTED: 'FILE_CORRUPTED',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_DOWNLOAD_FAILED: 'FILE_DOWNLOAD_FAILED',
  FILE_PROCESSING_FAILED: 'FILE_PROCESSING_FAILED',
  STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',

  // Network & Communication Errors
  NETWORK_ERROR: 'NETWORK_ERROR',
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  NETWORK_CONNECTION_REFUSED: 'NETWORK_CONNECTION_REFUSED',
  NETWORK_DNS_FAILED: 'NETWORK_DNS_FAILED',
  NETWORK_SSL_ERROR: 'NETWORK_SSL_ERROR',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  SMS_SEND_FAILED: 'SMS_SEND_FAILED',
  PUSH_NOTIFICATION_FAILED: 'PUSH_NOTIFICATION_FAILED',

  // Rate Limiting & Throttling
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  THROTTLE_LIMIT_EXCEEDED: 'THROTTLE_LIMIT_EXCEEDED',
  API_QUOTA_EXCEEDED: 'API_QUOTA_EXCEEDED',
  REQUEST_TOO_FREQUENT: 'REQUEST_TOO_FREQUENT',

  // Security Errors
  SECURITY_VIOLATION: 'SECURITY_VIOLATION',
  SECURITY_SUSPICIOUS_ACTIVITY: 'SECURITY_SUSPICIOUS_ACTIVITY',
  SECURITY_CSRF_TOKEN_INVALID: 'SECURITY_CSRF_TOKEN_INVALID',
  SECURITY_XSS_ATTEMPT: 'SECURITY_XSS_ATTEMPT',
  SECURITY_SQL_INJECTION_ATTEMPT: 'SECURITY_SQL_INJECTION_ATTEMPT',
  SECURITY_BRUTE_FORCE_ATTEMPT: 'SECURITY_BRUTE_FORCE_ATTEMPT',
  SECURITY_MALICIOUS_REQUEST: 'SECURITY_MALICIOUS_REQUEST',

  // System & Infrastructure Errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  MAINTENANCE_MODE: 'MAINTENANCE_MODE',
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE',
  RESOURCE_EXHAUSTED: 'RESOURCE_EXHAUSTED',
  MEMORY_LIMIT_EXCEEDED: 'MEMORY_LIMIT_EXCEEDED',
  CPU_LIMIT_EXCEEDED: 'CPU_LIMIT_EXCEEDED',
  DISK_SPACE_EXHAUSTED: 'DISK_SPACE_EXHAUSTED',

  // Verification & Validation
  VERIFICATION_ERROR: 'VERIFICATION_ERROR',
  VERIFICATION_CODE_INVALID: 'VERIFICATION_CODE_INVALID',
  VERIFICATION_CODE_EXPIRED: 'VERIFICATION_CODE_EXPIRED',
  VERIFICATION_EMAIL_NOT_SENT: 'VERIFICATION_EMAIL_NOT_SENT',
  VERIFICATION_PHONE_NOT_SENT: 'VERIFICATION_PHONE_NOT_SENT',
  VERIFICATION_ALREADY_VERIFIED: 'VERIFICATION_ALREADY_VERIFIED',

  // Webhook & Integration Errors
  WEBHOOK_DELIVERY_FAILED: 'WEBHOOK_DELIVERY_FAILED',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  WEBHOOK_RETRY_EXCEEDED: 'WEBHOOK_RETRY_EXCEEDED',
  INTEGRATION_CONFIGURATION_ERROR: 'INTEGRATION_CONFIGURATION_ERROR',
  INTEGRATION_AUTHENTICATION_FAILED: 'INTEGRATION_AUTHENTICATION_FAILED',

  // Cache & Performance Errors
  CACHE_ERROR: 'CACHE_ERROR',
  CACHE_CONNECTION_FAILED: 'CACHE_CONNECTION_FAILED',
  CACHE_KEY_NOT_FOUND: 'CACHE_KEY_NOT_FOUND',
  CACHE_TTL_EXPIRED: 'CACHE_TTL_EXPIRED',
  PERFORMANCE_DEGRADED: 'PERFORMANCE_DEGRADED',
  RESPONSE_TIME_EXCEEDED: 'RESPONSE_TIME_EXCEEDED',

  // Compliance & Legal Errors
  COMPLIANCE_VIOLATION: 'COMPLIANCE_VIOLATION',
  LEGAL_RESTRICTION: 'LEGAL_RESTRICTION',
  DATA_RETENTION_POLICY_VIOLATION: 'DATA_RETENTION_POLICY_VIOLATION',
  PRIVACY_POLICY_VIOLATION: 'PRIVACY_POLICY_VIOLATION',
  GDPR_VIOLATION: 'GDPR_VIOLATION',
  CCPA_VIOLATION: 'CCPA_VIOLATION',
} as const;

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum;
